version: '3.3'

services:
  video_portal_backend:
    image: ckala62rus/video_portal_backend:latest
    build: docker/php
    container_name: video_portal_backend
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - mysql_video_portal_backend
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx_video_portal_backend:
    image: nginx:1.21.1
    container_name: nginx_video_portal_backend
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./backend/:/var/www
    depends_on:
      - video_portal_backend
    environment:
      NGINX_UPSTREAM: video_portal_backend:9000

  mysql_video_portal_backend:
    image: mysql:8.0.26
    container_name: mysql_video_portal_backend
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/mysql/:/var/lib/mysql:rw
      - ./docker/mysql/logs/:/var/log/mysql:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
      - MYSQL_DATABASE=docker-boilerplate
      - MYSQL_USER=docker-boilerplate
      - MYSQL_PASSWORD=docker-boilerplate

  phpmyadmin_video_portal_backend:
    image: phpmyadmin
    container_name: phpmyadmin-new-template
#    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_video_portal_backend

  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server --address 0.0.0.0:9002 --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9002/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./storage/data:/data
    ports:
      # Bind explicitly to 127.0.0.1
      - "127.0.0.1:9002:9002"
      - "9001:9001"

  nginx_minio:
    image: nginx:1.19.2-alpine
    container_name: nginx_minio
    volumes:
      - ./docker/nginx-minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "88:88"
    depends_on:
      - minio
