name: Build and Publish Docker Images

on:
  pull_request:
    branches: [ main ]

jobs:
  video_portal_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry ( video_portal_backend )
        uses: docker/build-push-action@v4
        with:
          file: ./docker/php/Dockerfile
          push: true
          tags: ckala62rus/video_portal_backend
